# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-04-16 13:43:12 +0300 by root:
gem "jekyll", "~> 3.7"

